// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var dialogues = Dialogues.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Dialogues
    {
        [JsonProperty("prelude")]
        public Prelude Prelude { get; set; }

        [JsonProperty("niveau_1")]
        public Niveau1 Niveau1 { get; set; }

        [JsonProperty("niveau_2")]
        public Niveau2[] Niveau2 { get; set; }

        [JsonProperty("niveau_3")]
        public Niveau2[] Niveau3 { get; set; }
    }

    public partial class Niveau1
    {
        [JsonProperty("dialogues")]
        public Niveau2[] Dialogues { get; set; }

        [JsonProperty("indices")]
        public Niveau2[] Indices { get; set; }
    }

    public partial class Niveau2
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("personnage")]
        public Personnage Personnage { get; set; }

        [JsonProperty("fr")]
        public string Fr { get; set; }

        [JsonProperty("en")]
        public string En { get; set; }

        [JsonProperty("extraOptions", NullValueHandling = NullValueHandling.Ignore)]
        public ExtraOptions ExtraOptions { get; set; }
    }

    public partial class ExtraOptions
    {
        [JsonProperty("prochaineCible", NullValueHandling = NullValueHandling.Ignore)]
        public string ProchaineCible { get; set; }

        [JsonProperty("contientChoix", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ContientChoix { get; set; }
    }

    public partial class Prelude
    {
        [JsonProperty("dialogues")]
        public Niveau2[] Dialogues { get; set; }

        [JsonProperty("choix")]
        public Dictionary<string, Choix> Choix { get; set; }
    }

    public partial class Choix
    {
        [JsonProperty("fr")]
        public string Fr { get; set; }

        [JsonProperty("en")]
        public string En { get; set; }

        [JsonProperty("estChoix")]
        public bool EstChoix { get; set; }

        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("cible")]
        public string Cible { get; set; }
    }

    public enum Personnage { Alaric, Empty, Foule, Vyktor };

    public partial class Dialogues
    {
        public static Dialogues FromJson(string json) => JsonConvert.DeserializeObject<Dialogues>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Dialogues self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                PersonnageConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class PersonnageConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Personnage) || t == typeof(Personnage?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "?????":
                    return Personnage.Empty;
                case "Alaric":
                    return Personnage.Alaric;
                case "Foule":
                    return Personnage.Foule;
                case "Vyktor":
                    return Personnage.Vyktor;
            }
            throw new Exception("Cannot unmarshal type Personnage");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Personnage)untypedValue;
            switch (value)
            {
                case Personnage.Empty:
                    serializer.Serialize(writer, "?????");
                    return;
                case Personnage.Alaric:
                    serializer.Serialize(writer, "Alaric");
                    return;
                case Personnage.Foule:
                    serializer.Serialize(writer, "Foule");
                    return;
                case Personnage.Vyktor:
                    serializer.Serialize(writer, "Vyktor");
                    return;
            }
            throw new Exception("Cannot marshal type Personnage");
        }

        public static readonly PersonnageConverter Singleton = new PersonnageConverter();
    }
}
